import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col gap-3 bg-warp-loop bg-cover bg-center h-screen justify-center px-10">
          <p className="text-white text-8xl font-extrabold">
            Vojtěch <span className="text-yellow-400">Kylar</span>
          </p>
          <h2 className="font-bold ml-2 text-white text-lg">Student</h2>
        </div>
      </main>
    </>
  );
}
